:app_title: SKIP - Social Knowledge & Innovation Platform   # SNS名の全文
:abbr_app_title: SKIP                                       # SNS名の略称
:contact_addr: info@openskip.org                            # SNS運営元の連絡メールアドレス
:contact_url: http://dev.openskip.org/                      # SNS運営元のウェブページのURL
:help_url: http://www.openskip.org/help                     # SNSのヘルプのURL
:initial_anntena: SKIPチーム                                # 初期登録されるアンテナの名称
:login_account: ログインID                                  # ログインアカウントの名称
:login_password: パスワード                                 # パスワード
:login_account_example:                                     # ログインアカウントのパスワードのサンプル
:footer_link: <a target="_blank" href="http://www.openskip.org/help">ヘルプ</a> - <a onclick="open_hiki();" href="#">Hiki記法</a> - <a onclick="open_rule();" href="#">利用規約</a> - <a onclick="open_site();" href="#">このサイトについて</a> - <a href="/develop">ご要望</a>
# フッターの１行目（ヘルプ・規約へのリンクなどを推奨）
:footer_contact: お問い合わせはこちら                       # フッターの２列目（提供元への連絡先などを推奨）
:footer_copyright: Since 2008 SKIP                          # フッターの３列目（提供もとの記載などを推奨）
:footer_image_url: /images/skip/powered_by_rails.gif        # フッター右側に表示する画像のURL
:not_blank_link_re: https?:\/\/dev(.openskip.org)?\/.*      # ブログ内のリンクで新しいウインドウを開かないでリンクをするURLの正規表現
:point_button: GoodJob                                      # エントリへのポイント評価の
