# SKIP(Social Knowledge & Innovation Platform)
# Copyright (C) 2008 TIS Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# 全体設定
stop_new_user:
  format: boolean
  default: false

# 各種文言の設定
app_title:
  default: SKIP - Social Knowledge & Innovation Platform   # システムの名称
abbr_app_title:
  default: SKIP                                            # システムの略称
contact_addr:
  default: youradmin@example.com
help_url:
  format: url
  allow_blank: true
  default: http://www.openskip.org/help                    # ヘルプのURL
initial_anntena:
  default: SKIPチーム                                      # 初期登録されるアンテナの名称
login_account:
  default: ログインID                                      # ログインアカウントの名称
footer_link:                                               #フッターの１行目（ヘルプ・規約へのリンクなどを推奨）
  default: >-
    <a target="_blank" href="http://www.openskip.org/help">ヘルプ</a> -
    <a onclick="open_hiki();" href="#">Hiki記法</a> - <a onclick="open_rule();" href="#">利用規約</a> -
    <a onclick="open_site();" href="#">このサイトについて</a> - <a href="/develop">ご要望</a>
footer_contact:
  default: お問い合わせはこちら                            # フッターの２列目（提供元への連絡先などを推奨）
footer_copyright:
  default: Since 2008 SKIP                                 # フッターの３列目（提供もとの記載などを推奨）
footer_image_link_url:
  format: url
  default: http://www.openskip.org/                        # フッター右側に表示する画像のリンクURL
point_button:
  default: GoodJob                                         # 記事へのポイント評価の

# メール関連の設定
mail_function_setting:    # メール関連項目の表示制御(メールアドレス変更、メール通知設定、メール送信履歴、(記事)連絡タグ)
  format: boolean
  default: false
smtp_settings_address:
  default: localhost
smtp_settings_port:
  format: int
  default: 25
smtp_settings_domain:
  default: localhost.localdomain
smtp_settings_user_name:
  default:
smtp_settings_password:
  default:
smtp_settings_authentication:
  format: symbol
  default:

# その他設定
antenna_default_group:             # 初期のアンテナに追加されるグループを指定(なければ空配列とする)
  serialized: true
  default:
  - skipdevelop
  - openskip
recent_date:                       # 最近を示す日数
  format: int
  default: 10

# feed設定
mypage_feed_default_limit:         # マイページで表示するRSSフィードの設定(デフォルトの1フィードあたりの最大表示件数)
  format: int
  default: 3
mypage_feed_timeout:       # マイページで表示するRSSフィードのタイムアウト(秒)
  format: int
  default: 7
# フィードの設定
# url:   フィードのURL
# title: フィードのタイトル(フィード内のタイトル以外のものを設定したい場合)
# limit: フィードの最大表示件数
mypage_feed_settings:
  serialized: true
  default:
  - :url: http://www.openskip.org/rss.xml
    :title: SKIPニュース
