# SKIP(Social Knowledge & Innovation Platform)
# Copyright (C) 2008 TIS Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# 各種文言の設定
app_title:
  default: SKIP - Social Knowledge & Innovation Platform   # SNS名の全文
abbr_app_title:
  default: SKIP                                            # SNS名の略称
contact_addr:
  default: info@openskip.org                               # SNS運営元の連絡メールアドレス
contact_url:
  default: http://dev.openskip.org/                        # SNS運営元のウェブページのURL
help_url:
  default: http://www.openskip.org/help                    # SNSのヘルプのURL
initial_anntena:
  default: SKIPチーム                                      # 初期登録されるアンテナの名称
login_account:
  default: ログインID                                      # ログインアカウントの名称
login_password:
  default: パスワード                                      # パスワード
login_account_example:                                     # ログインアカウントのパスワードのサンプル
  default:
footer_link:                                               #フッターの１行目（ヘルプ・規約へのリンクなどを推奨）
  default: >-
    <a target="_blank" href="http://www.openskip.org/help">ヘルプ</a> -
    <a onclick="open_hiki();" href="#">Hiki記法</a> - <a onclick="open_rule();" href="#">利用規約</a> -
    <a onclick="open_site();" href="#">このサイトについて</a> - <a href="/develop">ご要望</a>
footer_contact:
  default: お問い合わせはこちら                            # フッターの２列目（提供元への連絡先などを推奨）
footer_copyright:
  default: Since 2008 SKIP                                 # フッターの３列目（提供もとの記載などを推奨）
footer_image_url:
  default: /custom/images/top_logo.png                     # フッター右側に表示する画像のURL
point_button:
  default: GoodJob                                         # エントリへのポイント評価の

# メール関連の設定
mail_function_setting:    # メール関連項目の表示制御(メールアドレス変更、メール通知設定、メール送信履歴、(エントリ)連絡タグ)
  format: boolean
  default: false
delivery_method:          # ActionMailer::Base.delivery_methodへの設定値
  default: test
smtp_settings_address:
  default: localhost
smtp_settings_port:
  default: 25
smtp_settings_domain:
  default: localhost.localdomain
smtp_settings_user_name:
  default:
smtp_settings_password:
  default:
smtp_settings_authentication:
  default:
raise_delivery_errors:    # ActionMailer::Base:raise_delivery_errorsへの設定値
  format: boolean
  default: false

# その他設定
develop_team_gid:                  # 要望、不具合受付グループのID
  default: skipteam
antenna_default_group:             # 初期のアンテナに追加されるグループを指定(なければ空配列とする)
  serialized: true
  default:
  - tcpdevelop
  - magazine
stop_new_user:
  format: boolean
  default: false

# feed設定
mypage_feed_default_limit:         # マイページで表示するRSSフィードの設定(デフォルトの1フィードあたりの最大表示件数)
  format: int
  default: 3
mypage_feed_timeout:       # マイページで表示するRSSフィードのタイムアウト(秒)
  format: int
  default: 7
# フィードの設定
# url:   フィードのURL
# title: フィードのタイトル(フィード内のタイトル以外のものを設定したい場合)
# limit: フィードの最大表示件数
mypage_feed_settings:
  serialized: true
  default:
  - :url: http://www.openskip.org/rss.xml
    :title: SKIPニュース
