# SKIP(Social Knowledge & Innovation Platform)
# Copyright (C) 2008 TIS Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# 各種文言の設定
app_title:
  default: SKIP - Social Knowledge & Innovation Platform   # SNS名の全文
abbr_app_title:
  default: SKIP                                            # SNS名の略称
contact_addr:
  default: info@openskip.org                               # SNS運営元の連絡メールアドレス
contact_url:
  default: http://dev.openskip.org/                        # SNS運営元のウェブページのURL
help_url:
  default: http://www.openskip.org/help                    # SNSのヘルプのURL
initial_anntena:
  default: SKIPチーム                                      # 初期登録されるアンテナの名称
login_account:
  default: ログインID                                      # ログインアカウントの名称
login_password:
  default: パスワード                                      # パスワード
login_account_example:                                     # ログインアカウントのパスワードのサンプル
  default:
footer_link:
  default: >-
    <a target="_blank" href="http://www.openskip.org/help">ヘルプ</a> -
    <a onclick="open_hiki();" href="#">Hiki記法</a> - <a onclick="open_rule();" href="#">利用規約</a> -
    <a onclick="open_site();" href="#">このサイトについて</a> - <a href="/develop">ご要望</a> #フッターの１行目（ヘルプ・規約へのリンクなどを推奨）
footer_contact:
  default: お問い合わせはこちら                            # フッターの２列目（提供元への連絡先などを推奨）
footer_copyright:
  default: Since 2008 SKIP                                 # フッターの３列目（提供もとの記載などを推奨）
footer_image_url:
  default: /images/skip/powered_by_rails.gif               # フッター右側に表示する画像のURL
not_blank_link_re:
  default: https?:\/\/dev(.openskip.org)?\/.*              # ブログ内のリンクで新しいウインドウを開かないでリンクをするURLの正規表現
point_button:
  default: GoodJob                                         # エントリへのポイント評価の

# 右上メニューの設定
main_menus:
  default:
  - :title: SKIPトップ
    :url:   http://www.openskip.org/
  - :title: SKIP開発SNS
    :url:   http://dev.openskip.org/
block_menus:
  default:
  - :id: link_menu
    :title: その他
    :margin_right: 0px
    :blocks:
    - :title: 開発
      :icon:  bullet_blue
      :links:
      - :title: Subversion
        :url:   http://svn.openskip.org/skip/
      - :title: redmine
        :url:   http://dev.openskip.org/redmine/
    - :title: 関連サイト
      :icon: bullet_green
      :links:
      - :title: Ruby On Rails
        :url:   http://www.rubyonrails.org/
      - :title: Ruby On Rails Help
        :url:   http://railshelp.com/
      - :title: HyperEstraier
        :url:   http://hyperestraier.sourceforge.net/

# メール関連の設定
mail_function_setting:    # メール関連項目の表示制御(メールアドレス変更、メール通知設定、メール送信履歴、(エントリ)連絡タグ)
  default: false
delivery_method:          # ActionMailer::Base.delivery_methodへの設定値
  default: :test
smtp_settings:            # ActionMailer::Base:smtp_settingsへの設定値
  default:
    :address: localhost
    :port: 25
    :domain: localhost.localdomain
    :user_name:
    :password:
    :authentication:
raise_delivery_errors:    # ActionMailer::Base:raise_delivery_errorsへの設定値
  default: false

# その他設定
password_edit_setting:             # パスワード変更可能かどうかの設定
  default: true
nickname_use_setting:              # ユーザ登録時にニックネームを利用するかどうかの設定
  default: true
ssl_setting:                       # SSLログインを利用するかどうかの設定
  default: false
full_text_search_setting:          # 全文検索入力欄の表示制御
  default: false
max_share_file_size:               # 共有ファイルの最大許可容量( 10M = 10485760 )
  default: 10485760
user_code_format_regex:            # ニックネームとして許可しない形式を指定
  default: ^(\d{6}|[kK]\d{5})$
develop_team_gid:                  # 要望、不具合受付グループのID
  default: skipteam
antenna_default_group:             # 初期のアンテナに追加されるグループを指定(なければ空配列とする)
  default:
  - tcpdevelop
  - magazine
mypage_feed_default_limit:         # マイページで表示するRSSフィードの設定(デフォルトの1フィードあたりの最大表示件数)
  default: 3
# フィードの設定
# url:   フィードのURL
# title: フィードのタイトル(フィード内のタイトル以外のものを設定したい場合)
# limit: フィードの最大表示件数
mypage_feed_settings:
  default:
  - :url: http://www.openskip.org/rss.xml
    :title: SKIPニュース
stop_new_user:
  default: true
